# Generated by Django 3.2 on 2021-11-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211116_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='department',
        ),
        migrations.AddField(
            model_name='communitydepartment',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.community'),
        ),
    ]
