# Generated by Django 3.2 on 2021-11-16 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registrationform_selfassessment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Major',
            new_name='College',
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name': 'College', 'verbose_name_plural': 'College'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'University'},
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='major',
            new_name='college1',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='college',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='major1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name="What's your major"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='message',
            field=models.TextField(verbose_name='Return Message'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='user',
            field=models.ForeignKey(help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
