# Generated by Django 3.2 on 2021-11-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211117_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='college1',
            new_name='college',
        ),
    ]
