# Generated by Django 3.2 on 2021-11-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_college1_userinformation_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='major1',
            new_name='major',
        ),
    ]
