# Generated by Django 3.2 on 2021-11-17 04:28

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_major1_userinformation_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Community'},
        ),
        migrations.AlterModelOptions(
            name='communitycategory',
            options={'verbose_name': 'CommunityCategory', 'verbose_name_plural': 'CommunityCategory'},
        ),
        migrations.AlterModelOptions(
            name='communitydepartment',
            options={'verbose_name': 'CommunityDepartment', 'verbose_name_plural': 'CommunityDepartment'},
        ),
        migrations.AlterModelOptions(
            name='registrationform',
            options={'verbose_name': 'RegistrationForm', 'verbose_name_plural': 'RegistrationForm'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name': 'UserInformation', 'verbose_name_plural': 'UserInformation'},
        ),
        migrations.AddField(
            model_name='userinformation',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.university'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='description',
            field=models.TextField(verbose_name="What's Up"),
        ),
        migrations.AlterField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='college',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=50, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='community',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.communitycategory', verbose_name='Community Category'),
        ),
        migrations.AlterField(
            model_name='community',
            name='images',
            field=models.JSONField(verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='community',
            name='information',
            field=models.TextField(verbose_name="What's Up"),
        ),
        migrations.AlterField(
            model_name='community',
            name='openUpDateEnd',
            field=models.DateTimeField(verbose_name='End Datetime of Recruiting New'),
        ),
        migrations.AlterField(
            model_name='community',
            name='openUpDateStart',
            field=models.DateTimeField(verbose_name='Start Datetime of Recruiting New'),
        ),
        migrations.AlterField(
            model_name='community',
            name='qqGroup',
            field=models.CharField(max_length=20, verbose_name='QQ Group Number'),
        ),
        migrations.AlterField(
            model_name='community',
            name='rank',
            field=models.FloatField(default=0.0, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='community',
            name='thumbnail',
            field=models.TextField(verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='information',
            field=models.TextField(verbose_name="What's Up"),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='logo',
            field=models.TextField(verbose_name='Logo of this category'),
        ),
        migrations.AlterField(
            model_name='communitydepartment',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.community', verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='communitydepartment',
            name='information',
            field=models.TextField(verbose_name="What's Up"),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.community', verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='department1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrationFormDepartment1', to='api.communitydepartment', verbose_name='Department1'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='department2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrationFormDepartment2', to='api.communitydepartment', verbose_name='Department2'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='whetherToAdjust',
            field=models.BooleanField(verbose_name='Whether To Adjust'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(verbose_name="What's Up"),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=api.models.UserGroupField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20, verbose_name='User Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isVerified',
            field=models.BooleanField(verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='joinedCommunities',
            field=models.ManyToManyField(to='api.Community', verbose_name='Joined Communities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='campus',
            field=models.ForeignKey(limit_choices_to={'university': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.university')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.college', verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=api.models.GenderField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='OTHERS', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='headPortrait',
            field=models.TextField(verbose_name='Head Portrait'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='national',
            field=models.CharField(max_length=50, verbose_name='National'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='nativePlace',
            field=models.CharField(max_length=50, verbose_name='Native Place'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='politicalLandscape',
            field=models.CharField(max_length=20, verbose_name='Political Landscape'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='User'),
        ),
    ]
