# Generated by Django 3.2 on 2021-11-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211117_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joinedCommunities',
            field=models.ManyToManyField(null=True, to='api.Community', verbose_name='Joined Communities'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campus', verbose_name='Campus'),
        ),
    ]
