# Generated by Django 3.2 on 2021-11-24 19:26

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='information',
            field=mdeditor.fields.MDTextField(verbose_name="What's Up"),
        ),
    ]
