# Generated by Django 3.2 on 2021-11-25 04:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_community_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='university',
        ),
        migrations.AlterField(
            model_name='campus',
            name='description',
            field=models.TextField(verbose_name='What’s Up'),
        ),
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(verbose_name='What’s Up'),
        ),
        migrations.AlterField(
            model_name='community',
            name='information',
            field=mdeditor.fields.MDTextField(verbose_name='What’s Up'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='information',
            field=models.TextField(verbose_name='What’s Up'),
        ),
        migrations.AlterField(
            model_name='communitydepartment',
            name='information',
            field=models.TextField(verbose_name='What’s Up'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(verbose_name='What’s Up'),
        ),
    ]
