# Generated by Django 3.2 on 2022-04-05 02:47

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211125_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='college',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='campus', chained_model_field='campus', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campus', verbose_name='College'),
        ),
    ]
