# Generated by Django 3.2 on 2022-04-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220405_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='api.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='college',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses', to='api.campus', verbose_name='Campus'),
        ),
    ]
