# Generated by Django 3.2 on 2022-04-05 03:30

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220405_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='campus',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='university', chained_model_field='university', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userinformation', to='api.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='college',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='campus', chained_model_field='campus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userinformation', to='api.college', verbose_name='College'),
        ),
    ]
