# Generated by Django 3.2 on 2022-04-05 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220405_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userinformation', to='api.university'),
        ),
    ]
