# Generated by Django 3.2 on 2022-04-05 03:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userinformation_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_set', to='api.university'),
        ),
        migrations.AlterField(
            model_name='community',
            name='campus',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='university', chained_model_field='university', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_set', to='api.campus', verbose_name='Campus'),
        ),
    ]
